### ISSUE TITLE
Proposal: add hiunnhue as a collaborator

### ISSUE THREAD

**Issue by yan12125** [chewing/ibus-chewing#108]
I have watched the ibus-chewing repository for a long time. In 2016, almost all pull requests are written by @hiunnhue. Seems he/she doesn't have write access to this repository yet? I proposed to add @hiunnhue as a collaborator, so that the ibus-chewing community can be even more prosperous!

**Comment by definite** [comment]
Excellent idea. The invitation is sent.

In fact, I also plan to migrate ibus-chewing to chewing organization for easier contribution and collaboration. I will start migration after 1.5.2 release.

**Comment by hiunnhue** [comment]
其實我沒學過程式，之前都是從現有的程式碼下去修改，先跑過 test 、自己用 checkinstall 裝起來試用，沒問題了才敢提 pull request ，所以最後還是要麻煩 definite 過目才行……

外行人這樣亂入實在抱歉，但新酷音真的是我目前最慣用的輸入法，所以才會自己試著修，把最煩人的 bug 解決，至於新功能的話，就要交給其他大大了。  :-)

**Comment by yan12125** [comment]
@hiunnhue 您過謙了 :)

**Comment by kidwm** [comment]
@hiunnhue 那有沒有興趣來幫忙修 PCManX 啊 XD

**Comment by hiunnhue** [comment]
看了一下 PCManX 的 Issue 清單… 感覺難度超高… 跟天書沒兩樣  Orz

而且我安裝套件庫裡面的 PCManX 1.3-1 ，可以開啟，但是只要連線就會崩潰，終端機顯示「程式記憶體區段錯誤 (core dumped) 」 ＠_＠

**Comment by kidwm** [comment]
@hiunnhue 系統也是 Fedora ?

**Comment by hiunnhue** [comment]
@kidwm 
用的是 elementary OS ，但我剛剛用 Live USB 試了發現可以正常連線，應該是我自己不知道亂搞了什麼，抱歉 Orz
