### ISSUE TITLE
Rename a file through GUI will clear the filename

### ISSUE THREAD

**Issue by chiawendt** [chewing/ibus-chewing#110]
**Environment**
Ubuntu 16.04 with the out of box desktop environment. 
libchewing3 0.4.0-4
ibus-chewing 1.4.14-4

**Reproduce the bug**
Right click a file. In the content menu select rename.  
This bug happens when the input method is ibus-chewing.
It does not happen when the input method is English.

**What is wrong?**
The filename is emptied.

**Screenshot**
https://i.imgur.com/k87yHfb.gif

**Comment by yan12125** [comment]
ibus-chewing and libchewing version?

**Comment by hiunnhue** [comment]
@q4w56 

Hi, the lates ibus-chewing (1.5.1) should have solved it.

**Comment by chiawendt** [comment]
[It works.](https://launchpad.net/ubuntu/zesty/amd64/ibus-chewing/1.5.1-1)  Thanks.
