### ISSUE TITLE
打不出ㄇㄛ˙發音

### ISSUE THREAD

**Issue by skygrango** [chewing/ibus-chewing#124]
如同題目所述，只要輸入完該ㄇㄛ˙，會直接消失

還有，我如果打"的"這個字，在選字時我的第9、0的字是白色方塊

如果還有哪些需要提供的資訊，請儘管說，感謝。

系統資訊
系統：Fedora27
linux核心：4.15.3-300.fc27.x86_64
已安裝的ibus套件資訊：
libusbx-1.0.21-4.fc27.x86_64
ibus-1.5.17-6.fc27.x86_64
libusb-0.1.5-10.fc27.x86_64
libusbmuxd-1.0.10-8.fc27.x86_64
ibus-gtk3-1.5.17-6.fc27.x86_64
ibus-qt-1.3.3-15.fc27.x86_64
ibus-setup-1.5.17-6.fc27.noarch
libusbx-1.0.21-4.fc27.i686
libuser-0.62-9.fc27.x86_64
ibus-libs-1.5.17-6.fc27.x86_64
ibus-chewing-1.6.1-1.fc27.x86_64
ibus-gtk2-1.5.17-6.fc27.x86_64
ibus-wayland-1.5.17-6.fc27.x86_64
libusal-1.1.11-37.fc27.x86_64

**Comment by hiunnhue** [comment]
@skygrango 

嗨，因為「ㄇㄛ˙」這個音是沒有字的，所以才會直接消失。

如果你想要打的是「麼」，按照[教育部字典](https://www.moedict.tw/麼)，正確的發音是「ㄇㄜ˙」

至於白色方塊，應該是因為你選用的字型無法顯示那兩個字，可以換個字型試試。


祝新年快樂 :-)

**Comment by skygrango** [comment]
哇，原來多年來都是打錯、唸錯的，受教了

感謝您辛勤的快速回覆，新年快樂 ：）

**Comment by hiunnhue** [comment]
@skygrango 

好像也不能完全說是正確或錯誤的問題… 

但新酷音核心 (libchewing) 目前似乎是儘量以教育部字典為標準，

所以只好請大家先照著教育部的標準音輸入了
