### ISSUE TITLE
ibus-chewing depends on gtk2

### ISSUE THREAD

**Issue by jbicha** [chewing/ibus-chewing#125]
ibus-chewing depends on gtk2, but gtk3 is the current stable supported version.

https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html

**Comment by cosimoc** [comment]
https://github.com/definite/ibus-chewing/pull/131 is a fix to this, and it would be awesome if it could go upstream :-)

**Comment by yan12125** [comment]
#131 has been merged yay!

**Comment by yan12125** [comment]
Hi is there a plan to release a new version supporting GTK 3? I'm one of the maintainers of [ibus-chewing](https://archlinux.org/packages/community/x86_64/ibus-chewing/) package on Arch Linux, and there is a [call](https://archlinux.org/todo/gtk-2-eol/) to drop GTK 2.

Update: see https://github.com/definite/ibus-chewing/issues/162
