### ISSUE TITLE
Word selection panel is broken in Chrome under 4k resolution.

### ISSUE THREAD

**Issue by Superdanby** [chewing/ibus-chewing#126]
## Basic Information
Operating System: Fedora 26 ~ 27
DE: Gnome 3.24 ~ 3.26, Wayland
ibus-chewing version: 1.6.1
Google Chrome: 65.0.3325.181 (Official Build) (64-bit)

## Problem Description
The word selection panel is shifted lower right when using 4k resolution. And it often moved beyond the screen edge so that I couldn't even look at what I am choosing. 

How reproducible: Always

Steps to reproduce:
1. Switch to 4k resolution.
2. Open a new Google Chrome.
3. Type a word and trigger the word selection panel. 

Actual results:
![image](https://user-images.githubusercontent.com/17717083/38179463-3af9c3f0-3656-11e8-853c-92e8aa74c11c.png)

Expected results:
![image](https://user-images.githubusercontent.com/17717083/38179480-71caf016-3656-11e8-9cb6-ef507bdca655.png)

**Comment by hiunnhue** [comment]
same issue ?
* https://github.com/libpinyin/ibus-libpinyin/issues/68
* https://github.com/ibus/ibus/issues/1988

**Comment by Superdanby** [comment]
Ah, yes. Thanks, I'll report this against the ibus issue instead.
