### ISSUE TITLE
Not working on gnome-terminal 3.30.1

### ISSUE THREAD

**Issue by chiawendt** [chewing/ibus-chewing#135]
No characters are emitted to gnome-terminal, neither in "English mode" nor in "Chinese mode" of ibus-chewing.

_Versions:_

4.18.12-arch
ibus-chewing 1.6.1-1
gnome-shell 3.30.0
gnome-terminal 3.30.1

**Comment by medicalwei** [comment]
I can confirm this on lxterminal and terminator.  Suppose that all libvte-based terminals are affected.

**Comment by medicalwei** [comment]
Also, this seems only happens in GNOME 3 under Wayland.

GNOME 3 started in Xorg also other desktop environments in Xorg (unsure about other display managers using Wayland) is unaffected.

**Comment by chiawendt** [comment]
This bug does not happen on my computer anymore.
