### ISSUE TITLE
How to upgrade ibus-chewing to 1.5.1 on Ubuntu 16.04?

### ISSUE THREAD

**Issue by AwinHuang** [chewing/ibus-chewing#137]
My ibus-chewing was fixed at 1.4.14, can not update by apt.

**Comment by hiunnhue** [comment]
嗨 @AwinHuang, 

你可以下載原始碼自己編譯安裝，或安裝 Debian 提供的 1.6.1 版的 .deb 套件檔，

或安裝 Ubuntu 19.04 提供的 1.6.1 版的 .deb 套件檔 (https://launchpad.net/ubuntu/+source/ibus-chewing)，

但我不知道這樣混用其他版本的 deb 檔會有什麼問題，你可能要自己承擔風險…
