### ISSUE TITLE
應該表示第幾頁

### ISSUE THREAD

**Issue by jidanni** [chewing/ibus-chewing#138]
應該表示第幾頁。如
![2](https://user-images.githubusercontent.com/1230959/48221677-afadbd80-e3cd-11e8-82aa-2f8106d093f1.jpg)
應該表示 1/10 等等…
(Let's say there are 100 choices. We want to know we are looking at the first page of 10.)

**Comment by medicalwei** [comment]
日文輸入法 mozc 應該是透過 `ibus_engine_update_auxiliary_text` 來顯示頁數的。
https://github.com/google/mozc/blob/master/src/unix/ibus/ibus_candidate_window_handler.cc

或許可以在換頁的時候做這個效果。

**Comment by definite** [comment]
@hiunnhue  Thanks for implement the function
