### ISSUE TITLE
中文模式下要是輸入數字，會變成英文模式

### ISSUE THREAD

**Issue by laichiaheng** [chewing/ibus-chewing#139]
中文打好好的，輸入右邊數字鍵的數字後，會切換到英文模式，還要按 shift 切換回來
OS: Ubuntu 18.10

**Comment by laichiaheng** [comment]
@hiunnhue 沒人有這個問題嗎？每次輸入數字都還要手動切換回中文超麻煩的

**Comment by hiunnhue** [comment]
嗨 @laichiaheng, 


你用的是 1.5.1 版嗎？ 這個問題應該已經在 1.5.1 之後的版本修理好了，目前最新的版本是 1.6.1 版。


如果 Ubuntu 18.10 的套件倉庫提供的還是 1.5.1 版，你可以下載原始碼自己編譯安裝，

或安裝 Debian 提供的 1.6.1 版的 .deb 套件檔，

或安裝 Ubuntu 19.04 提供的 1.6.1 版的 .deb 套件檔：https://launchpad.net/ubuntu/+source/ibus-chewing


但是…我不知道這樣混用別的發行版的套件會不會有問題，你要自己承擔風險…

**Comment by laichiaheng** [comment]
更新後問題已解決
