### ISSUE TITLE
常常會有方塊字的出現，選框還會出現在很遠的地方

### ISSUE THREAD

**Issue by laichiaheng** [chewing/ibus-chewing#141]
OS: Ubuntu 18.10
![2018-12-14 20-57-01](https://user-images.githubusercontent.com/9532105/50004717-09b02d00-ffe3-11e8-8089-1a9c5a08c9ef.png)

**Comment by hiunnhue** [comment]
hi @laichiaheng, 

候選清單出現在很遠的地方，這個可能是 ibus 本身的問題，ibus-chewing 這邊可能沒辦法解決。你可以試試其他 ibus 的輸入法，例如 ibus-cangjie (倉頡)、ibus-array (行列)，我猜應該有相同的現象…

至於方塊的問題，應該是因為你使用的字型沒辦法顯示那些字，請到 ibus 的偏好設定，選擇有支援那些字的字型。

![image](https://user-images.githubusercontent.com/1015601/50041652-2146ee80-0093-11e9-8d40-f4b5804438da.png)

**Comment by laichiaheng** [comment]
@hiunnhue 改成 Noto Sans CJK TC Regular 後還是一樣，這應該是支援最廣的字體了？
話說 Ubuntu 好像預設就是 Noto Sans CJK TC

**Comment by hiunnhue** [comment]
Hi @laichiaheng, 

我不確定，但 Gnome 環境好像是用自己的 ibus 選字界面，所以不受 ibus 偏好設定視窗控制。

另外我試了一下，原本也不能顯示「𢔨」和「𢔶」這兩個字，後來安裝了全字庫的字體就可以顯示了，所以思源黑體應該是沒有支援這兩個字沒錯。你也可以安裝看看全字庫字體、花園明朝體、一點明體等等。

**Comment by laichiaheng** [comment]
@hiunnhue 他們有辦法直接經由 apt 安裝嗎？

**Comment by hiunnhue** [comment]
全字庫宋體 fonts-cns11643-sung
花園明朝體似乎是 fonts-hanazono，不確定
一點明體應該沒有在套件庫裡面

套件庫裡面沒有的字型也可以手動安裝，詳細步驟你 google 一下應該就有了
