### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [chewing/ibus-chewing#150]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by yan12125** [comment]
https://fedora.zanata.org is now down. That seems to be related to broken builds - after running `cmake -B build -S . && make -C build`, `build/po/*.po` contain no translated strings. I workarounded that by copying files after cmake and before make
```
touch build/po/ibus-chewing.pot
cp -v po/*.po build/po/
```

**Comment by Jibec** [comment]
kind reminder, zanata will be removed in a few weeks now https://fedoraproject.org/wiki/Changes/Zanata_removal

**Comment by kanru** [comment]
Hey @Jibec it's been a while after this ticket was opened. Can I still migrate to the new translation platform?

**Comment by Jibec** [comment]
Of course! Please send an email to "trans" mailing list to get some help, a few people there will be able to help you :)
Jean-Baptiste

**Comment by rffontenelle** [comment]
As mentioned in the [mailing list](https://lists.fedoraproject.org/archives/list/trans@lists.fedoraproject.org/thread/7MFQ542IW3DKJ36ADRY7QEOXXYO4AUZ3/),  the translation project and component are set.

https://translate.fedoraproject.org/projects/ibus-chewing/
