### ISSUE TITLE
最新 git 版後方選詞出現大問題

### ISSUE THREAD

**Issue by laichiaheng** [chewing/ibus-chewing#154]
兩個字為一組的詞無法個別來選字，譬如「測試」兩字，我想要把第二個字改成「是」會沒辦法，永遠只能夠兩個字一起選，不管怎麼按右鍵都無效。
ibus-chewing 版本：1.6.1+12+gc1e7f0d-1

就算下載 git 版來測試也一樣

**Comment by yan12125** [comment]
我在1.6.1+12+gc1e7f0d-1 (編譯自 c1e7f0d97aa8bb1a1166621c3f0780daa0db06c1 )也遇到相同問題。一個解法是：打完「測試」後，按一下右方向鍵，讓游標移到「測」和「試」的中間，再按一下Tab，「測」跟「試」就可以分開選字了。穩定版本(1.6.1)是按兩次下就可以選第二個字。

**Comment by hiunnhue** [comment]
我快速的試了一下…… 我用的是 git 編譯的最新版，沒有用舊版來比對，只有和 pime-chewing 和 微軟新注音比較… 所以我不知道 ibus-chewing 新舊版之間有沒有差別。
　
但我猜應該是你勾選了「後方選詞」功能？ 
　
傳統（用微軟新注音）選字的時候，我們會手動按 ← 鍵把游標回到要選的字的左邊 。例如「我愛你」，如果你要選字的是「我」，就必須要把游標移動到「我」的左邊 : 

> |我愛你

如果你要選的剛好是最後一個字，你可以直接按↓鍵，但其實你會看見游標自動往左挪了一個字：

> 我愛|你

如果你要選的是詞，就必須手動把游標挪到整個詞的前面：

> |騎士

　
而「後方選詞」功能讓你省去把游標挪到詞頭的步驟。如果它判斷游標目前的位置剛好是某個詞的詞尾，那麼它就會自動跳到詞頭，然後開啟選字：

> 當時很多男孩的夢想是成為騎士|

例如你在句尾按↓，游標就會左移一字，變成 `|騎士`，然後開啟選詞。

如果你想要選的是「士」，那就在選詞的狀態再次按「↓」，就會從選詞變成選字。

那如果你想要選的是「騎」，那就手動把游標移動到 `|騎士`，然後開啟選字。

<br>

我自己是覺得用不太習慣，所以我沒有開啟，這樣就會比較接近傳統的選字法。
你可以到設定那邊把「後方選詞」取消掉再用用看。

**Comment by laichiaheng** [comment]
> 我快速的試了一下…… 我用的是 git 編譯的最新版，沒有用舊版來比對，只有和 pime-chewing 和 微軟新注音比較… 所以我不知道 ibus-chewing 新舊版之間有沒有差別。
> 　
> 但我猜應該是你勾選了「後方選詞」功能？
> 　
> 傳統（用微軟新注音）選字的時候，我們會手動按 ← 鍵把游標回到要選的字的左邊 。例如「我愛你」，如果你要選字的是「我」，就必須要把游標移動到「我」的左邊 :
> 
> > |我愛你
> 
> 如果你要選的剛好是最後一個字，你可以直接按↓鍵，但其實你會看見游標自動往左挪了一個字：
> 
> > 我愛|你
> 
> 如果你要選的是詞，就必須手動把游標挪到整個詞的前面：
> 
> > |騎士
> 
> 　
> 而「後方選詞」功能讓你省去把游標挪到詞頭的步驟。如果它判斷游標目前的位置剛好是某個詞的詞尾，那麼它就會自動跳到詞頭，然後開啟選字：
> 
> > 當時很多男孩的夢想是成為騎士|
> 
> 例如你在句尾按↓，游標就會左移一字，變成 `|騎士`，然後開啟選詞。
> 
> 如果你想要選的是「士」，那就在選詞的狀態再次按「↓」，就會從選詞變成選字。
> 
> 那如果你想要選的是「騎」，那就手動把游標移動到 `|騎士`，然後開啟選字。
> 
> 我自己是覺得用不太習慣，所以我沒有開啟，這樣就會比較接近傳統的選字法。
> 你可以到設定那邊把「後方選詞」取消掉再用用看。

他是預設開啟的，以前也沒有這些問題

**Comment by yan12125** [comment]
比較了 1.6.1 版與 1.6.1+12+gc1e7f0d 之間的一些版本之後，我發現目前這個現象是從 70a1935290c9e8bcb8e098b91711f97269619c6f 開始。如果在 git 版本的基礎上，將 70a1935290c9e8bcb8e098b91711f97269619c6f revert，就和 1.6.1 版的「後方選詞」功能表現相同：在「測試」後方按 ↓，出現的選單包含所有讀音為ㄘㄜˋㄕˋ的二字詞，再按一次 ↓，則是選擇第二個字，包含所有讀音為ㄕˋ的字。該 commit 似乎是讓方向鍵用來選詞？如此一來， ↓ 就沒有辦法用來切換選詞和選字了。

另外，70a1935290c9e8bcb8e098b91711f97269619c6f 也使 ibus-chewing 內建的測試程式失敗：
```
$ GSETTINGS_SCHEMA_DIR="$PWD/bin/" make test
Running tests...
Test project /build/ibus-chewing/src/ibus-chewing/build
    Start 1: MakerDialogUtil
1/5 Test #1: MakerDialogUtil ..................   Passed    0.01 sec
    Start 2: MakerDialogBackend
2/5 Test #2: MakerDialogBackend ...............   Passed    0.15 sec
    Start 3: IBusChewingUtil
3/5 Test #3: IBusChewingUtil ..................   Passed    0.20 sec
    Start 4: IBusChewingPreEdit
4/5 Test #4: IBusChewingPreEdit ...............Subprocess terminated***Exception:   0.17 sec

** (/usr/bin/gtester:2601): WARNING **: 19:38:57.791: Deprecated: Since GLib 2.62, gtester and gtester-report are deprecated. Port to TAP.
TEST: /build/ibus-chewing/src/ibus-chewing/build/test-bin/IBusChewingPreEdit-test... (pid=2602)
key_press_from_key_sym(35(5),0), buffer=|ㄓ| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|ㄓㄨ| outgoing=||
key_press_from_key_sym(2f(/),0), buffer=|ㄓㄨㄥ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|中| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|中ㄨ| outgoing=||
key_press_from_key_sym(70(p),0), buffer=|中ㄨㄣ| outgoing=||
key_press_from_key_sym(36(6),0), buffer=|中文| outgoing=||
key_press_from_key_sym(ff0d(Return),0), buffer=|| outgoing=|中文|
key_press_from_key_sym(77(w),0), buffer=|ㄊ| outgoing=||
key_press_from_key_sym(38(8),0), buffer=|ㄊㄚ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|它| outgoing=||
key_press_from_key_sym(ff54(Down),0), buffer=|它| outgoing=||
key_press_from_key_sym(32(2),0), buffer=|他| outgoing=||
key_press_from_key_sym(31(1),0), buffer=|他ㄅ| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|他ㄅㄨ| outgoing=||
key_press_from_key_sym(36(6),0), buffer=|他不| outgoing=||
key_press_from_key_sym(35(5),0), buffer=|他不ㄓ| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|他不ㄓㄨ| outgoing=||
key_press_from_key_sym(2f(/),0), buffer=|他不ㄓㄨㄥ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|他不中| outgoing=||
key_press_from_key_sym(ff54(Down),0), buffer=|他不中| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|他不重| outgoing=||
key_press_from_key_sym(3c(<),1), buffer=|他不重，| outgoing=||
key_press_from_key_sym(77(w),0), buffer=|他不重，ㄊ| outgoing=||
key_press_from_key_sym(38(8),0), buffer=|他不重，ㄊㄚ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|他不重，它| outgoing=||
key_press_from_key_sym(67(g),0), buffer=|他不重，它ㄕ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|他不重，他是| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|他不重，他是ㄨ| outgoing=||
key_press_from_key_sym(69(i),0), buffer=|他不重，他是ㄨㄛ| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|他不重，他是我| outgoing=||
key_press_from_key_sym(76(v),0), buffer=|他不重，他是我ㄒ| outgoing=||
key_press_from_key_sym(6d(m),0), buffer=|他不重，他是我ㄒㄩ| outgoing=||
key_press_from_key_sym(2f(/),0), buffer=|他不重，他是我ㄒㄩㄥ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|他不重，他是我兄| outgoing=||
key_press_from_key_sym(32(2),0), buffer=|他不重，他是我兄ㄉ| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|他不重，他是我兄ㄉㄧ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|他不重，他是我兄弟| outgoing=||
key_press_from_key_sym(3e(>),1), buffer=|他不重，他是我兄弟。| outgoing=||
key_press_from_key_sym(ff0d(Return),0), buffer=|| outgoing=|他不重，他是我兄弟。|
key_press_from_key_sym(35(5),0), buffer=|ㄓ| outgoing=||
key_press_from_key_sym(6b(k),0), buffer=|ㄓㄜ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|這| outgoing=||
key_press_from_key_sym(67(g),0), buffer=|這ㄕ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|這是| outgoing=||
key_press_from_key_sym(ffe1(Shift_L),0), buffer=|這是| outgoing=||
key_press_from_key_sym(69(i),0), buffer=|這是i| outgoing=||
key_press_from_key_sym(62(b),0), buffer=|這是ib| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|這是ibu| outgoing=||
key_press_from_key_sym(73(s),0), buffer=|這是ibus| outgoing=||
key_press_from_key_sym(2d(-),0), buffer=|這是ibus-| outgoing=||
key_press_from_key_sym(63(c),0), buffer=|這是ibus-c| outgoing=||
key_press_from_key_sym(68(h),0), buffer=|這是ibus-ch| outgoing=||
key_press_from_key_sym(65(e),0), buffer=|這是ibus-che| outgoing=||
key_press_from_key_sym(77(w),0), buffer=|這是ibus-chew| outgoing=||
key_press_from_key_sym(69(i),0), buffer=|這是ibus-chewi| outgoing=||
key_press_from_key_sym(6e(n),0), buffer=|這是ibus-chewin| outgoing=||
key_press_from_key_sym(67(g),0), buffer=|這是ibus-chewing| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|這是ibus-chewing | outgoing=||
key_press_from_key_sym(ffe1(Shift_L),0), buffer=|這是ibus-chewing | outgoing=||
key_press_from_key_sym(67(g),0), buffer=|這是ibus-chewing ㄕ| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|這是ibus-chewing ㄕㄨ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|這是ibus-chewing 書| outgoing=||
key_press_from_key_sym(62(b),0), buffer=|這是ibus-chewing 書ㄖ| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|這是ibus-chewing 書ㄖㄨ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|這是ibus-chewing 輸入| outgoing=||
key_press_from_key_sym(7a(z),0), buffer=|這是ibus-chewing 輸入ㄈ| outgoing=||
key_press_from_key_sym(38(8),0), buffer=|這是ibus-chewing 輸入ㄈㄚ| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|這是ibus-chewing 輸入法| outgoing=||
key_press_from_key_sym(ff0d(Return),0), buffer=|| outgoing=|這是ibus-chewing 輸入法|
key_press_from_key_sym(75(u),0), buffer=|ㄧ| outgoing=||
key_press_from_key_sym(6a(j),0), buffer=|ㄨ| outgoing=||
key_press_from_key_sym(69(i),0), buffer=|ㄨㄛ| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|我| outgoing=||
key_press_from_key_sym(72(r),0), buffer=|我ㄐ| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|我ㄐㄧ| outgoing=||
key_press_from_key_sym(38(8),0), buffer=|我ㄐㄧㄚ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|我家| outgoing=||
key_press_from_key_sym(61(a),0), buffer=|我家ㄇ| outgoing=||
key_press_from_key_sym(70(p),0), buffer=|我家ㄇㄣ| outgoing=||
key_press_from_key_sym(36(6),0), buffer=|我家門| outgoing=||
key_press_from_key_sym(66(f),0), buffer=|我家門ㄑ| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|我家門ㄑㄧ| outgoing=||
key_press_from_key_sym(30(0),0), buffer=|我家門ㄑㄧㄢ| outgoing=||
key_press_from_key_sym(36(6),0), buffer=|我家門前| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|我家門前ㄧ| outgoing=||
key_press_from_key_sym(2e(.),0), buffer=|我家門前ㄧㄡ| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|我家門前有| outgoing=||
key_press_from_key_sym(76(v),0), buffer=|我家門前有ㄒ| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|我家門前有ㄒㄧ| outgoing=||
key_press_from_key_sym(6c(l),0), buffer=|我家門前有ㄒㄧㄠ| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|我家門前有小| outgoing=||
key_press_from_key_sym(63(c),0), buffer=|我家門前有小ㄏ| outgoing=||
key_press_from_key_sym(6b(k),0), buffer=|我家門前有小ㄏㄜ| outgoing=||
key_press_from_key_sym(36(6),0), buffer=|我家門前有小河| outgoing=||
key_press_from_key_sym(3c(<),1), buffer=|我家門前有小河，| outgoing=||
key_press_from_key_sym(63(c),0), buffer=|我家門前有小河，ㄏ| outgoing=||
key_press_from_key_sym(2e(.),0), buffer=|我家門前有小河，ㄏㄡ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|我家門前有小河，後| outgoing=||
key_press_from_key_sym(61(a),0), buffer=|我家門前有小河，後ㄇ| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|我家門前有小河，後ㄇㄧ| outgoing=||
key_press_from_key_sym(30(0),0), buffer=|我家門前有小河，後ㄇㄧㄢ| outgoing=||
key_press_from_key_sym(34(4),0), buffer=|我家門前有小河，後面| outgoing=||
key_press_from_key_sym(75(u),0), buffer=|我家門前有小河，後面ㄧ| outgoing=||
key_press_from_key_sym(2e(.),0), buffer=|我家門前有小河，後面ㄧㄡ| outgoing=||
key_press_from_key_sym(33(3),0), buffer=|我家門前有小河，後面有| outgoing=||
key_press_from_key_sym(67(g),0), buffer=|我家門前有小河，後面有ㄕ| outgoing=||
key_press_from_key_sym(30(0),0), buffer=|我家門前有小河，後面有ㄕㄢ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|我家門前有小河，後面有山| outgoing=||
key_press_from_key_sym(71(q),0), buffer=|我家門前有小河，後面有山ㄆ| outgoing=||
key_press_from_key_sym(69(i),0), buffer=|我家門前有小河，後面有山ㄆㄛ| outgoing=||
key_press_from_key_sym(20(space),0), buffer=|我家門前有小河，後面有山坡| outgoing=||
key_pres**
ERROR:/build/ibus-chewing/src/ibus-chewing/test/IBusChewingPreEdit-test.c:37:assert_substring: assertion failed (subStr == needle): ("\345\213\242" == "\344\270\226")
GTester: last random seed: R02Sccbada07a140d67a641fe142d0ed75cb

    Start 5: ibus-chewing-engine
5/5 Test #5: ibus-chewing-engine ..............   Passed    0.06 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   0.59 sec

The following tests FAILED:
          4 - IBusChewingPreEdit (Subprocess terminated)
Errors while running CTest
make: *** [Makefile:159: test] Error 8
```

**Comment by laichiaheng** [comment]
> 我快速的試了一下…… 我用的是 git 編譯的最新版，沒有用舊版來比對，只有和 pime-chewing 和 微軟新注音比較… 所以我不知道 ibus-chewing 新舊版之間有沒有差別。
> 　
> 但我猜應該是你勾選了「後方選詞」功能？
> 　
> 傳統（用微軟新注音）選字的時候，我們會手動按 ← 鍵把游標回到要選的字的左邊 。例如「我愛你」，如果你要選字的是「我」，就必須要把游標移動到「我」的左邊 :
> 
> > |我愛你
> 
> 如果你要選的剛好是最後一個字，你可以直接按↓鍵，但其實你會看見游標自動往左挪了一個字：
> 
> > 我愛|你
> 
> 如果你要選的是詞，就必須手動把游標挪到整個詞的前面：
> 
> > |騎士
> 
> 　
> 而「後方選詞」功能讓你省去把游標挪到詞頭的步驟。如果它判斷游標目前的位置剛好是某個詞的詞尾，那麼它就會自動跳到詞頭，然後開啟選字：
> 
> > 當時很多男孩的夢想是成為騎士|
> 
> 例如你在句尾按↓，游標就會左移一字，變成 `|騎士`，然後開啟選詞。
> 
> 如果你想要選的是「士」，那就在選詞的狀態再次按「↓」，就會從選詞變成選字。
> 
> 那如果你想要選的是「騎」，那就手動把游標移動到 `|騎士`，然後開啟選字。
> 
> 我自己是覺得用不太習慣，所以我沒有開啟，這樣就會比較接近傳統的選字法。
> 你可以到設定那邊把「後方選詞」取消掉再用用看。

而且這更新也有個大問題，你只能改第二個字而不能改第一個字，所以你的方法無效……
但有個新的發現，要是選擇空白鍵選字，除了按下空白鍵外，也可以按五下「↓」來選字

**Comment by hiunnhue** [comment]
> 你只能改第二個字而不能改第一個字

可以的！！！！！

覺得好像有點難解釋…… 不同長度的詞算是不同的清單，或是你可以理解成不同的頁。

<br>

（ 以下都是關閉後方選詞 ）

以 `|台北市` 為例，一開始打開的清單會是：

> 1. 台北市   2. 臺北市     [←] [ →]   

然後再按一次選字鍵就會切換到下一個長度的清單，所以打開的是：

> 1. 台北   2. 臺北     [←] [ →]   

再按一次選字，又切到下個長度，所以變成：

> 1. 台   2. 臺   3. 抬   4. 颱   5. 苔   6. 邰   7. 跆   8. 檯   9. 薹    [←] [ →]

如果是直式的，看起來就會像是這樣：

```
 1. 台
 2. 臺
 3. 抬
 4. 颱
 5. 苔
 6. 邰
 7. 跆
 8. 檯
 9. 薹
[↑] [↓]
 ```

你會發現，在舊版，不管你是直式橫式，其實都是 ← → 鍵換頁，

因為↓鍵是固定拿來開啟選單、切換選詞長度，而↑鍵是關閉選字。

<br>

可是既然現在要逐一選擇，方向鍵的作用就勢必要配合選單的方向而改變，

因此橫式的時候，左右鍵不再是直接換頁，而是移動光標，直到頭尾字才會換頁；

直式的時候，上下鍵也不再是開關選字、切換選詞長度，而是移動光標，直到頭尾字才換頁。

<br>

至於「切換選詞長度」的功能，就被安排成「換頁」；

每當來到某個長度的最後一頁時，再次換頁就會來到下一個長度：

以 `|台北市` 為例，你不斷的左右移動光標來換頁，就會在這3個長度不斷切換

> 1 台北市   2. 臺北市   [←] [ →]
> 1 台北   2. 臺北   [←] [ →]
> 1 台   2. 臺   3. 抬   4. 颱   5. 苔   6. 邰   7. 跆   8. 檯   9. 薹    [←] [ →]   (一字的第一頁)
>   .........
> 1 齝   2. 坮  3. 枱   4. 炲   5. 菭   6. 擡   7. 呞   8. 䔶   9. 㘆    [←] [ →]   (一字的最後一頁)

<br>

直式的時候就是上下移動光標來換頁、切換長度。

<br>

我去比較了 pime-chewing 方式，我覺得和目前 git 版的方式雖然有一點小差異，但還滿相近的。

主要的差異是，

ibus-chewing 在直式的時候用上下鍵移動光棒，左右鍵直接換頁；橫式的時候左右鍵移動光標，下鍵直接換頁。

**Comment by yan12125** [comment]
> 可是既然現在要逐一選擇，方向鍵的作用就勢必要配合選單的方向而改變

感謝詳細的解說！看到這一句終於懂了。和之前的習慣不同，讓我以為是 bug。或許可以考慮在 README.md, ChangeLog 或 RELEASE-NOTES.txt 加入說明？

另外有兩個小問題：

1. 在LXQt中，選字的光棒未顯示。圖中的程式為Firefox 84.0.2

![screen](https://user-images.githubusercontent.com/1937689/104046919-c3f2dc80-521b-11eb-9740-5dc56afe81a9.png)

2. 當「空白鍵選字」未啟用時， `|台北市` 的情況下 ↓ 只能選擇三個字的詞，無法用左右鍵切換到二字詞或一字詞。

**Comment by laichiaheng** [comment]
> 例如你在句尾按↓，游標就會左移一字，變成 |騎士，然後開啟選詞。

這沒問題

> 如果你想要選的是「士」，那就在選詞的狀態再次按「↓」，就會從選詞變成選字。

這無效

**Comment by laichiaheng** [comment]
> > 你只能改第二個字而不能改第一個字
> 
> 可以的！！！！！
> 
> 覺得好像有點難解釋…… 不同長度的詞算是不同的清單，或是你可以理解成不同的頁。
> 
> （ 以下都是關閉後方選詞 ）
> 
> 以 `|台北市` 為例，一開始打開的清單會是：
> 
> > 1. 台北市   2. 臺北市     [←] [ →]
> 
> 然後再按一次選字鍵就會切換到下一個長度的清單，所以打開的是：
> 
> > 1. 台北   2. 臺北     [←] [ →]
> 
> 再按一次選字，又切到下個長度，所以變成：
> 
> > 1. 台   2. 臺   3. 抬   4. 颱   5. 苔   6. 邰   7. 跆   8. 檯   9. 薹    [←] [ →]
> 
> 如果是直式的，看起來就會像是這樣：
> 
> ```
>  1. 台
>  2. 臺
>  3. 抬
>  4. 颱
>  5. 苔
>  6. 邰
>  7. 跆
>  8. 檯
>  9. 薹
> [↑] [↓]
> ```
> 
> 你會發現，在舊版，不管你是直式橫式，其實都是 ← → 鍵換頁，
> 
> 因為↓鍵是固定拿來開啟選單、切換選詞長度，而↑鍵是關閉選字。
> 
> 可是既然現在要逐一選擇，方向鍵的作用就勢必要配合選單的方向而改變，
> 
> 因此橫式的時候，左右鍵不再是直接換頁，而是移動光標，直到頭尾字才會換頁；
> 
> 直式的時候，上下鍵也不再是開關選字、切換選詞長度，而是移動光標，直到頭尾字才換頁。
> 
> 至於「切換選詞長度」的功能，就被安排成「換頁」；
> 
> 每當來到某個長度的最後一頁時，再次換頁就會來到下一個長度：
> 
> 以 `|台北市` 為例，你不斷的左右移動光標來換頁，就會在這3個長度不斷切換
> 
> > 1 台北市   2. 臺北市   [←] [ →]
> > 1 台北   2. 臺北   [←] [ →]
> > 1 台   2. 臺   3. 抬   4. 颱   5. 苔   6. 邰   7. 跆   8. 檯   9. 薹    [←] [ →]   (一字的第一頁)
> > .........
> > 1 齝   2. 坮  3. 枱   4. 炲   5. 菭   6. 擡   7. 呞   8. 䔶   9. 㘆    [←] [ →]   (一字的最後一頁)
> 
> 
> 直式的時候就是上下移動光標來換頁、切換長度。
> 
> 我去比較了 pime-chewing 方式，我覺得和目前 git 版的方式雖然有一點小差異，但還滿相近的。
> 
> 主要的差異是，
> 
> ibus-chewing 在直式的時候用上下鍵移動光棒，左右鍵直接換頁；橫式的時候左右鍵移動光標，下鍵直接換頁。

不管按上下左右永遠都會是三個字呀，並不會進入所謂下一層的清單

**Comment by hiunnhue** [comment]
@yan12125 

> 在LXQt中，選字的光棒未顯示。

對，上一次的 commit 沒有改到，現在還沒 merge 的 PR #152 就是讓光棒顯示的

<br><br>

@yan12125  @laichiaheng 

> 當「空白鍵選字」未啟用時， |台北市 的情況下 ↓ 只能選擇三個字的詞，無法用左右鍵切換到二字詞或一字詞。

> 不管按上下左右永遠都會是三個字呀，並不會進入所謂下一層的清單

yan12125 抓出癥結點了！ 😲   平常我都有勾空白鍵選字，所以用起來都沒問題

有空的時候再來研究看看要怎麼改……

**Comment by laichiaheng** [comment]
> @yan12125
> 
> > 在LXQt中，選字的光棒未顯示。
> 
> 對，上一次的 commit 沒有改到，現在還沒 merge 的 PR #152 就是讓光棒顯示的
> 
> 
> 
> @yan12125 @laichiaheng
> 
> > 當「空白鍵選字」未啟用時， |台北市 的情況下 ↓ 只能選擇三個字的詞，無法用左右鍵切換到二字詞或一字詞。
> 
> > 不管按上下左右永遠都會是三個字呀，並不會進入所謂下一層的清單
> 
> yan12125 抓出癥結點了！ astonished 平常我都有勾空白鍵選字，所以用起來都沒問題
> 
> 有空的時候再來研究看看要怎麼改……

請問選字光棒是代表說能夠上下選字囉？

**Comment by hiunnhue** [comment]
嗨 @yan12125 @laichiaheng

方便的話，可以麻煩抽空試試看 Pull Request 有沒有解決問題嗎？ 感謝。

**Comment by laichiaheng** [comment]
@hiunnhue 這個問題已經解決滿久了
