### ISSUE TITLE
請問可以修復 Wayland 下無法輸入中文的問題嗎？

### ISSUE THREAD

**Issue by laichiaheng** [chewing/ibus-chewing#161]
在 Wayland 下除非使用 Xorg 程式，啟用了 XWayland，否則 ibus-chewing 永遠無法輸入中文。

**Comment by hiunnhue** [comment]
@laichiaheng 

嗨…你可以說一下哪些程式不能用嗎… 我目前用的是 elementary OS，都沒有遇到這方面的問題

昨天我也稍微試用了一下 Fedora 35 的 Live USB（Fedora 35 預設是使用 Wayland 的？），好像也可以正常打字…

**Comment by laichiaheng** [comment]
> @laichiaheng
> 
> 嗨…你可以說一下哪些程式不能用嗎… 我目前用的是 elementary OS，都沒有遇到這方面的問題
> 
> 昨天我也稍微試用了一下 Fedora 35 的 Live USB（Fedora 35 預設是使用 Wayland 的？），好像也可以正常打字…

所有沒用到 XWayland 的程式都不行，但是一旦有程式使用過 XWayland，之後就可以用了。
Fedora 用的是 ibus-libzhuyin 而非 ibus-chewing。（libzhuyin 選字選詞有夠糟糕）
我是用 Arch Linux，順帶一提，ibus-anthy 和 ibus-chewing 一樣也不行，但是 ibus-mozc 和 ibus-libzhuyin 就都可以。

**Comment by hiunnhue** [comment]
@laichiaheng 

我在 Fedora 35 Live USB 用的也是 ibus-chewing，我開機之後直接安裝，沒有多做其他的步驟。

現在我正在試用 Manjaro Gnome，也是開機之後直接安裝，也是可以正常使用的（見底下截圖）

我不懂 Wayland 方面的事情，但如果按照你說的，"有程式使用過 XWayland" 或重新啟動 ibus 框架就可以的話，是不是一開始沒有啟動到
 > ibus-x11
 > ibus-extensions-gtk3

之類的？

你可以列舉幾個會用到 XWayland 的程式嗎？ 

![Screenshot from 2022-02-12 17-00-51](https://user-images.githubusercontent.com/1015601/153722018-5250c4d5-b0fb-4478-9864-4f30375e724b.png)

**Comment by laichiaheng** [comment]
@hiunnhue `Firefox` 沒指定 Wayland 就會使用 Xwayland，`chewing-editor` 應該也是 Xwayland，`Gnome Terminal` 理應是 Wayland，但他也會讓中文輸入成功啟用，記得 `Gedit` 好像也會（更正，並不會），但他應該也是 Wayland 才對？
基本上你裡面那個 ibus-x11 使用 Gnome Wayland 時都不會自己出現。
![2022-02-15 09-06-30 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/153973147-238306e7-9a95-4a88-b8bd-5e905aca8d4a.png)

右上角永遠只會顯示個「酷」
![2022-02-15 09-05-23 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/153973027-b1447b74-3422-4819-881e-45a2fda66005.png)

開啟 chewing-editor 後
![2022-02-15 09-08-13 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/153973311-eef9df0f-4b1f-43f8-8222-a3e128428331.png)


對了，我之前的暫時解決方式是在 `/etc/xdg/autostart/` 自己加入以下的檔案
```[Desktop Entry]
Type=Application
Name=IBus Daemon
Exec=ibus-daemon -drxR
```

話說 Fedora 應該是個很活躍的開發者平台，怎麼會改用比較難用的 ibus-libzhuyin？而且也沒人發現 ibus-chewing 在 Wayland 的問題？

**Comment by hiunnhue** [comment]
@laichiaheng 

我剛剛又試用了一次 Fedora Live USB，用了 ibus-anthy，也還是可以正常輸入啊… 不需要額外做什麼… 

實在不知道你的問題出在哪裡… 有其他朋友和你遇到一樣的狀況嗎？

**Comment by laichiaheng** [comment]
@hiunnhue Anthy 那個我記錯了，她只有概覽搜尋框不行，其他都 OK，看起來是 ibus-chewing 專屬的問題。
不過目前已經找到了比較好的替代方案，ibus-rime 的洋蔥 mix-in 輸入法真的是太強大了，居然可以同時間輸入中英日韓文不用切換輸入法。
