### ISSUE TITLE
Any plan to tag a new version?

### ISSUE THREAD

**Issue by binotaliu** [chewing/ibus-chewing#162]
Hi there, 
It has been **6 years** since last time this repository got a version tag. While [in this period, many new feature / bug fixes got merged](https://github.com/definite/ibus-chewing/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+created%3A%3E2016-06-17). There are even [a milestone that been named `1.6.1`](https://github.com/definite/ibus-chewing/milestone/4?closed=1), but there was never a `1.6.1` version been tagged.

While [the development of this project seems very inactive now](https://github.com/definite/ibus-chewing/graphs/code-frequency), and looks like some people (for example, [the author of this comment](https://github.com/definite/ibus-chewing/issues/161#issuecomment-1046044633)) has already give up from using `ibus-chewing`, and I personally don't use bopomofo anymore.
But, recently, I set up a GNU/Linux environment for my non-tech friend. So I try to install `ibus-chewing` for them. It's very frustration to use. Some UX-improvement feature, like #147 and #152, has been merged but you can't use it if you don't compile `ibus-chewing` by yourself!

While there are many alternative options such as `ibus-rime` etc., or you can even just don't use `ibus` and instead use `fcitx`. But I believe `ibus` is still widely used and actively maintained, [elementary os even integrated ibus into their system](https://github.com/elementary/switchboard-plug-keyboard/blob/c9dc4a83ee52c67e090969a96e0cb6ed322a3a9f/src/Views/InputMethod.vala#L19), and `ibus-chewing`'s user experience is more familiar for those who come from Windows into GNU/Linux. So it would be nice if we can just have a new version tagged and people can just use the newer, better version. 

Edited: math

**Comment by lunarythia** [comment]
@hiunnhue @definite 上一個commit是兩年前，上一個更新是**七年前**！

**Comment by yan12125** [comment]
1.6.2 is out :tada:
