### ISSUE TITLE
[feature] 新酷音輸入法預設使用英文模式

### ISSUE THREAD

**Issue by hwhsu1231** [chewing/ibus-chewing#164]
## 描述

在 Windows 中使用微軟中文輸入法時，我的習慣是將預設輸入法設為【**中文(繁體,台灣)**】，並且預設使用【**英文模式**】。這樣一來，每當我開啟終端機並輸入一些 CLI 命令時，就可以直接輸入英文。然後，當我要在瀏覽器或編輯器中輸入中文的時候，只需要按下【Shift】鍵就可以切換成輸入中文。

然而，我在 Ubuntu 下卻找不到【**將新酷音輸入法設定成預設使用英文模式**】的方法，而且它預設使用的是【**中文模式**】。雖然目前的替代方案是，透過【**Super+Space**】直接切換成英文和 ibus 新酷音輸入法，可是這不符合我的習慣。

如果說 ibus 新酷音早已經提供了這種設定，麻煩告知我如何操作。如果沒有，希望能加入這種設定選項。

## 版本

- **OS:** Ubuntu 22.04
- **ibus:** 1.5.26-4 amd64
- **ibus-chewing:** 1.6.1-2 amd64

**Comment by kanru** [comment]
用【Shift】或是【CapsLock】把輸入模式切到英文後，應該就會預設是英文了。

如果他會自己切回中文的話，建議把「Caps Lock 與輸入法狀態同步」關掉。
