### ISSUE TITLE
Add back systray icons

### ISSUE THREAD

**Issue by kanru** [chewing/ibus-chewing#177]
>  Is it intended to remove many icons? I tried current git-master (4f8f25c) and found icons are missing in several places.

_Originally posted by @yan12125 in https://github.com/chewing/ibus-chewing/issues/172#issuecomment-1930421928_

GtkStatusIcon is deprecated in GTK3 and removed from GTK4.

The replacement libindicator was unmaintained. The forked project libayatana-indicator does not support GTK4 yet (https://github.com/AyatanaIndicators/libayatana-appindicator/issues/22)

The only path forward to restore systray icons is to either

1. Partially implement the SNI (StatusNotifierItem) protocol by ourselves.
2. Ship the tray icon as a separate binary that links to GTK3

**Comment by kanru** [comment]
Alternatively we can revert the engine program back to GTK3 but the setup program to GTK4

**Comment by kanru** [comment]
看起來 ibus 也有自己的 systray？需要測試一下其他的 desktop 因為我太久只用 gnome 了

**Comment by yan12125** [comment]
> 看起來 ibus 也有自己的 systray？需要測試一下其他的 desktop 因為我太久只用 gnome 了

是的。若使用 ibus-chewing 1.6.2，切換到新酷音之後可以看到兩個 XEmbed systray：

![圖片](https://github.com/chewing/ibus-chewing/assets/1937689/f7eb67e4-dede-4fe5-bb75-0c7993af090b)

第一個可能是 ibus-daemon 本身的 systray，第二個是顯示目前的中/英與全形/半形模式（分別可用滑鼠左鍵及右鍵切換）。

而在 4f8f25c 上，第一個 systray 不再顯示藍底白字的「酷」圖示，也沒有第二個 systray。

我使用的是 LXQt on X11。

> Partially implement the SNI (StatusNotifierItem) protocol by ourselves.

FWIW, some people consider SNI obsolete and were discussing a new spec: https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84

**Comment by kanru** [comment]
![Uploading Screenshot from 2024-02-08 00-03-24.png…]()

**Comment by kanru** [comment]
![Screenshot from 2024-02-08 00-03-24](https://github.com/chewing/ibus-chewing/assets/17571/1cfbeca8-ef6a-4afa-bb4c-7a8831d4f466)

**Comment by kanru** [comment]
晚點來看，可能可以利用 ibus 自己的  tray

**Comment by yan12125** [comment]
感謝提到屬性面版。不過我自己並不使用 ibus-chewing, 只是 [Arch Linux 軟體包](https://archlinux.org/packages/extra/x86_64/ibus-chewing/) 的維護者。日常使用的人的意見更為重要。

**Comment by yan12125** [comment]
> 第二個是顯示目前的中/英與全形/半形模式（分別可用滑鼠左鍵及右鍵切換）。

新的 systray 似乎沒有這項功能。或許可以在 change log 加以說明，並提到這是移除 X11 dependency 必要的妥協？
