### ISSUE TITLE
Icon missing in IBus setup

### ISSUE THREAD

**Issue by yan12125** [chewing/ibus-chewing#181]
在最新的 git-master 上，「IBus 偏好設定」(`ibus-setup`) 中新酷音的 icon 不見了。以下分別是 1.6.2 與 4f8f25c 的截圖：

![2024-02-07_16-37](https://github.com/chewing/ibus-chewing/assets/1937689/fce76381-5b3b-48df-94eb-98cc42f94248)

![2024-02-07_16-38](https://github.com/chewing/ibus-chewing/assets/1937689/1e03c5e4-6269-411b-876a-0d51ae069d04)

可能和 https://github.com/chewing/ibus-chewing/pull/172 有關。

**Comment by kanru** [comment]
可能跟 #184 有關，應該修好了

**Comment by yan12125** [comment]
謝謝！我在農曆新年後可以再測試。

**Comment by yan12125** [comment]
Thanks! I can confirm the icon is back in ibus-setup with ibus-chewing 2.0.0 rc1.
