### ISSUE TITLE
Update changelog to mention changes to systray behavior

### ISSUE THREAD

**Issue by kanru** [chewing/ibus-chewing#190]
> 顯示目前的中/英與全形/半形模式（分別可用滑鼠左鍵及右鍵切換）。
> 新的 systray 似乎沒有這項功能。或許可以在 change log 加以說明，並提到這是移除 X11 dependency 必要的妥協？

_Originally posted by @yan12125 in https://github.com/chewing/ibus-chewing/issues/177#issuecomment-1940657067_

**Comment by hiunnhue** [comment]
我平常是用 Pantheon (elementary OS) 和 Gnome，所以也沒用 ibus 自己的系統匣圖示了。


![image](https://github.com/chewing/ibus-chewing/assets/1015601/419e6c3e-3a52-4276-a567-51005248b2b6)

我剛剛用 Xfce 快速看了一下，看起來是這樣子的：

1. 深藍色的【酷】是 ibus 自帶的傳統系統匣的輸入法圖示，如果你有安裝其他輸入法，例如倉頡、行列，滑鼠點這個圖示可以切換輸入法。

3. 水藍色的【中】是 ibus-chewing 自己做的中英、全半形切換圖示。

4. 沒有傳統系統匣的環境 ( 例如 Pantheon、Gnome 3 )，會改用其他工具 ( 不確定是否叫 Indicator ) 來顯示和切換輸入法。這些工具不見得會吃你在 ibus-setup 的設定，例如 Gnome 3 的就無視，但 Panthon 就有。

5. 雖然不知道怎麼辦到的，但 Anthy 或 SKK 日文輸入法也可以用 ibus 自帶傳統系統匣圖示來顯示英數、全半形。切換到 Anthy 或 SKK 時，會暫時顯示 Anthy 或 SKK 的圖示，然後自動轉為 `_A` ，代表半形英文模式。如果 ibus-chewing 也能實做，就可以割捨水藍色的圖示。

6. Gnome Indicator(?) 也可以同時用來顯示、切換輸入法和英數模式、全半形模式。


綜合上述：
無論是在傳統系統匣的環境，或是現代的 Indicator 環境，只要能像 Anthy、SKK 那樣，利用輸入法圖示同時顯示英數、全半形，那捨棄 ibus-chewing 自產的水藍色圖示應該是沒什麼大問題的。

唯一失去的是「用滑鼠左鍵快速切換中英、右鍵快速切換全半形」的功能，一律都要展開選單。

**Comment by kanru** [comment]
> 雖然不知道怎麼辦到的，但 Anthy 或 SKK 日文輸入法也可以用 ibus 自帶傳統系統匣圖示來顯示英數、全半形。切換到 Anthy 或 SKK 時，會暫時顯示 Anthy 或 SKK 的圖示，然後自動轉為 _A ，代表半形英文模式。如果 ibus-chewing 也能實做，就可以割捨水藍色的圖示。

v2.0.0-rc1 用的正是跟 Anthy 一樣的方法

ibus 的 tray 還是可以左鍵選單裡面選擇要用什麼輸入模式，真有需要滑鼠快速切換的話也可以把浮動屬性欄叫出來

![Screenshot from 2024-02-14 20-41-45](https://github.com/chewing/ibus-chewing/assets/17571/226cb347-b1ff-4d11-80e4-945145e9f394) ![Screenshot from 2024-02-14 20-41-53](https://github.com/chewing/ibus-chewing/assets/17571/3d41af07-2bf0-4fc8-84a5-a91d98b13eb1)
