### ISSUE TITLE
Hsu keyboard "g" "e" problem 

### ISSUE THREAD

**Issue by chtsao** [chewing/ibus-chewing#203]
Your kind help is deeply appreciated. 

After recent update (It worked fine), I can no longer input the character such as 季。Using Hsu keyboard, 
* It goes with "g" "e" then "j" (select the fourth tone). It does show ㄐ and ㄧ, but they all disappear once "j" inputted.  
* It seems worked fine when using standard keyboard setting. 
* My system:  kernel: 6.9.1-arch1-1 arch: x86_64 bits: 64 compiler: gcc
    v: 14.1.1;   Desktop: Xfce v: 4.18.1 Distro: Arch Linux
* Added to .baschr "export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx"
  
Thanks again.

**Comment by kanru** [comment]
Looks like the same issue as https://github.com/chewing/libchewing/issues/546

It should be fixed once [libchewing 0.8.2](https://github.com/chewing/libchewing/releases/tag/v0.8.2) reaches Arch.

**Comment by chtsao** [comment]
Thanks a lot your prompt response and quick fix. I will wait for libchewing 0.8.2 then. Thanks!

**Comment by chtsao** [comment]
Thanks a lot. Problem solved by 
updating to extra/libchewing 0.8.2-1 [installed]
    Intelligent Chinese phonetic input method.
ibus-chewing +Hsu keyboard is certainly one of the most helpful Chinese input tools for me. Deeply appreciated.

**Comment by chtsao** [comment]
Sorry. Further testing revealed that there are still problems when inputting 
間 or 借
using Hsu keyboard. Your kind help is deeply appreciated.
---
extra/libchewing 0.8.2-1 [installed]

**Comment by kanru** [comment]
@chtsao please provide the input sequence to help debug 🙏🏼

**Comment by chtsao** [comment]
gen(space) 1st tone 
gee(j)           4th tone
gued [绝]

**Comment by chtsao** [comment]
extra/ibus-chewing 2.0.0-1 [installed]
間 絕 借 problem solved. Thanks a lot!
ps. Is there any way I can buy you cups of coffee :)?

**Comment by kanru** [comment]
Help us spread the word about chewing 👍🏼
