### ISSUE TITLE
Possibility and benifits of adopting C23 standard

### ISSUE THREAD

**Issue by wdhongtw** [chewing/ibus-chewing#206]
想討論是否該轉移至 C23 標準來建置此專案。

## Motivation

想嘗試加上 `clang` / `gcc` 均有支援的 `-Wextra` (以及開啟 `-Werror`)，藉由引入更多檢查來避免未來的人為錯誤 / 提昇專案品質。
不過在嘗試開啟的過程中，有多兩類錯誤目前沒什麼好的處理方法。

第一類是 `unused-parameter`，主要出現於寫入設定的 callback `*_apply_callback`。
(雖然這些 code 在 Kan-Ru 最近的努力重構下，未來應該都不需要了。)
這些 parameter 可以透過 `__attribute__((unused))` 來明確告知 compiler 用不到，
不過比較漂亮的寫法還是需要 C23 才支援的 `[[maybe_unused]]`

第二類是 `missing-field-initializers`，有的可以直接用 C99 及支援的 designated initializer 處理。
不過有的地方需要 `NULL`-terminated array ，這邊受至於 GTK API 的 convention。
e.g. `entries` for `g_option_context_add_main_entries`.
在 C23 可以使用 empty initializer 之前，沒什麼好的方式表達這種... "有各式各樣 member / nested struct 的 `NULL`-terminated array"。

## Discussion

我已經在 Fedora 40 上測試過，用起來沒什麼問題。且目前 CI 是跑在 `fedora:latest` 上，應該是可以無痛轉換。

綜上所述，考量到 C23 可以用比較漂亮的方式來達成啟用 `-Wextra` 的目標，想討論是否已經是好的時間點做此改動。

## References

- https://en.cppreference.com/w/c/compiler_support/23
- https://clang.llvm.org/docs/AttributeReference.html
- https://en.cppreference.com/w/c/language/struct_initialization
- https://docs.gtk.org/glib/method.OptionContext.add_main_entries.html

**Comment by kanru** [comment]
你好！

我的私心是全部用 rust 改寫 🙈 

我覺得開啟 `-Wextra` 跟 `-Werror` 都不是問題，`-Werror` 可能會在 compiler 升級的時候導致編譯失敗，可以先開啟起來看看。

關於使用 C23 的功能，只要主流發行版的 gcc/clang 都有支援就沒問題 (Arch/Fedora/FreeBSD/Debian/Ubuntu)

**Comment by wdhongtw** [comment]
已發 PR  :D

這次使用的到的新寫法有二

- `[[maybe_unused]]`: 這個在 GCC/Clang 均是已支援很長時間，應該沒問題
- empty initializer: 這個可能會有爭議，若有疑慮可以退回舊版寫法並稍加改進
  - Clang 是 17 開始支援，而 Debian 的 llvm 套件看起來只到 14
  - GCC 只找的到 C++ 的支援頁面，不太確定狀況...

---

各發行版的 GCC/Clang 版本:

- FreeBSD (Latest): gcc 9-15, llvm 11-18
- Arch (Latest): gcc 13-14, llvm 17-18
- Fedora 40: gcc 14, llvm 18
- Ubuntu 24.04: gcc 13, llvm 18
- Debian 12.0: gcc 12, llvm 14

Clang and GCC compliance page:

- https://clang.llvm.org/c_status.html#c2x
- https://gcc.gnu.org/projects/cxx-status.html

**Comment by wdhongtw** [comment]
> 我的私心是全部用 rust 改寫 🙈

我也對 Rust 的使用感到非常興奮，不過以 ibus plugin 這種會有很多 higher order function 的使用情境，有點擔心會對可讀性造成不良影響。
Golang x C 因為 calling convention 不同，要跨語言傳遞 function 的開發體驗很不好，不確定 Rust x C 會不會有類似的問題。

**Comment by yan12125** [comment]
Please don't use `-Werror`. Major compiler upgrades (ex: GCC 13 -> 14) often bring new warnings (sometimes false positives due to compiler bugs), breaking the build.

**Comment by wdhongtw** [comment]
> Please don't use `-Werror`. Major compiler upgrades (ex: GCC 13 -> 14) often bring new warnings (sometimes false positives due to compiler bugs), breaking the build.

Yes, that do happen, and I just hit my own knee in the PR above. :crying_cat_face:

**Comment by yan12125** [comment]
Is `-Werror` added to avoid unnoticed warnings in CI? If so, some GitHub actions may be used to make warnings more visible. Something here may be cool: https://www.google.com/search?q=github%20actions%20gcc%20warnings&ie=utf-8&client=firefox-b-m

**Comment by wdhongtw** [comment]
@yan12125

The idea that make warning into error is helpful in my past team work experience.

```
[submit / modify PR] --> [CI check] -passed-> [review PR] -passed-> [merge] --> [[done]]
                                   |-failed-> [modify]   |-failed-> [modify]
```

It force the person who is modifying the code to ensure the CI pass, otherwise the PR is never reviewed.
In this way the maintainer / reviewer don't need to spend time on incomplete PR.

"Making warnings more visible" is something like JUnit report integration / coverage integration.
It make the cooperation experience better, but it's still different from "making the CI job fail".

That's the motivation to introduce `-Werror` here.

---

@kanru

但實物上運作確實沒那麼美好，我在公司也常常要幫別人看 pipeline fail。
昨天 PR 還讓 Kan-Ru 幫看 job log，增加 maintainer 負擔，這並非我的本意。

如果這樣作法 and/or 負面影響，不是 maintainer 樂見的，還請指教。 :crying_cat_face:
如果不加 `-Werror`, `unused-parameter` 相關 warning 大概也都不用處理，上面那個 PR 改動會少很多。

**Comment by yan12125** [comment]
> That's the motivation to introduce `-Werror` here.

Got it, thank you for detailed information. I have another suggestion - see https://github.com/chewing/ibus-chewing/pull/207/files#r1665750234

**Comment by yan12125** [comment]
I think this is done and the issue can be closed?

**Comment by kanru** [comment]
Fixed by #207
