### ISSUE TITLE
Page_Down Key Event may cause libchewing to panic

### ISSUE THREAD

**Issue by sonata-chen** [chewing/ibus-chewing#221]
我嘗試輸入中文字「他」，使用下方向鍵叫出候選字選單後，按下「下方向鍵」或 Page_Down 換頁時，從最後一頁換回第一頁時，有機會導致 libchewing panic。以下是能夠用來重現這個問題的按鍵序列：

1. process_key_event(-,77(w),11,0)
2. process_key_event(-,38(8),9,0)
3. process_key_event(-,20(space),39,0)
4. process_key_event(-,ff51(Left),69,0)
5. process_key_event(-,ff54(Down),6c,0)
6. process_key_event(-,ff56(Page_Down),6d,0)
7. process_key_event(-,ff56(Page_Down),6d,0)

[Full logs](https://gist.github.com/sonata-chen/b4b564ec8825aa2a1b142d9bdf3a6ef2)

我有注意到 ibus-chewing 收到 Page_Down 按鍵，前後兩次的反應不一樣。第一次是送給 libchewing `key-K61-PageDown`，第二次是
`key-K57-Down`。

環境：Arch Linux, KDE, Wayland, ibus-chewing v2.1.0-rc.1, libchewing v0.9.0-rc.2

**Comment by kanru** [comment]
感謝，我也有發現這個問題，下一個 libchewing RC 就會修掉。
