### ISSUE TITLE
ibus-chewing crashes gedit in search box while window out of focus

### ISSUE THREAD

**Issue by zerng07** [chewing/ibus-chewing#28]
Version: ibus-chewing 1.4

How to reproduce:
1. Open gedit
2. Press Ctl+F to open the search box
3. Switch input method to ibus-chewing
4. Enter any chinese character, for example "找"
5. Press Alt+Tab or Hover the mouse to Hot Corner of GNOME Shell
6. gedit crashed

**Comment by definite** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1182813

**Comment by definite** [comment]
It looks more than gedit bug than ibus-chewing, seem it does not handle the preedit buffer properly.

I can, however, mitigate this problem by adding an option that clean the preedit buffer on focus out event, just like ibus-libpinyin does.

**Comment by definite** [comment]
mitigated with commit c51ad13292f739790494b8b22a23b35a04e2cd9e

**Comment by definite** [comment]
Note that you need to turn on "Clean pre-edit buffer when focus out" to mitigate this issue.
