### ISSUE TITLE
Support KB_THL_PINYIN and KB_MPS2_PINYIN

### ISSUE THREAD

**Issue by czchen** [chewing/ibus-chewing#35]
KB_THL_PINYIN = 台灣華語羅馬拼音
KB_MPS2_PINYIN = 注音二式

These two keyboard layout are added in libchewing 0.3.4. Please help to add them to ibus-chewing, thanks.

**Comment by definite** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1182819
