### ISSUE TITLE
「↑鍵」收起候選字清單不完全

### ISSUE THREAD

**Issue by hiunnhue** [chewing/ibus-chewing#38]
步驟：
1. 按 ↓ 鍵叫出候選字清單
2. 按 ↑ 鍵關閉候選字清單
3. 清單上的字消失，只剩下清單本身

類似情況：
1. 以 shift + 方式輸入標點符號，例如 shift + < 輸入全形逗號
2. 候選字清單自動開啟，但上面沒有任何候選字，需要再按 ↓ 鍵才會出現候選字

環境A：
- ubuntu 13.04
- ibus-chewing: 1.4.3-1ubuntu1
- libchewing3: 0.3.5-chewing+938+201309250347~ubuntu13.04.1 (from PPA)

環境B：
- elementary os (based on ubuntu 12.04)
- ibus: 1.4.1-3ubuntu1
- ibus-chewing: 1.3.10+clean-2ubuntu1  or  1.4.3-1ubuntu1
- libchewing3: 0.3.5-chewing+1015+201311041845~ubuntu12.04.1 (from PPA)

![candidate](https://f.cloud.github.com/assets/1015601/1216475/b3ed1814-268b-11e3-8c60-0ef9d354da1f.png)
![candidate_list](https://f.cloud.github.com/assets/1015601/1475568/9b24e89e-463d-11e3-95d8-50e9f4182355.png)

**Comment by definite** [comment]
Fixed in ibus-chewing-1.4.14
