### ISSUE TITLE
顯示語言/全半形/設定的bar行蹤不定

### ISSUE THREAD

**Issue by PHR2014** [chewing/ibus-chewing#46]
想要請問

我剛升級到Ubuntu 14.04
在打字的時候
原本會乖巧出現在角落的bar現在變成想出現就出現
通常是出現在滑鼠游標之後
可是它說來就來說走就走很難控制
有辦法可以固定它嗎？

謝謝!

**Comment by definite** [comment]
兩個問題：
1. ibus-chewing-1.4.14 還有這個問題嗎？
2. 桌面環境是什麼？(GNOME/KDE/Cinnamon/...)

**Comment by PHR2014** [comment]
（1）我現在是使用Ubuntu 14.04，情況還是一樣。在使用libreoffice的時候那個 
bar基本上是出現在游標處（時在、時消失），經常擋住我的文件內容（沒辦法移 
開）。

（2）我的桌面環境是GNOME。

希望可以改善
謝謝！

**Comment by kidwm** [comment]
@PHR2014 GNOME Shell 不是有整合 ibus 語言列了嗎？

**Comment by definite** [comment]
現在即使不在 Gnome 下，那個語言列也已經不見了。
倒是可以在ibus那裡啟用「在應用程式視窗內嵌預先編輯文字」
