### ISSUE TITLE
CHEWING_DATADIR CMake variable name mismatch

### ISSUE THREAD

**Issue by obache** [chewing/ibus-chewing#47]
In CMakeList.txt, CHEWING_DATADIR is supposed as pointing datadir of chewing, but PKG_CONFIG  (in MagageDependency of cmake-fedora) define it as CHEWING_chewing_DATADIR.

**Comment by lantw44** [comment]
This problem causes the following error message:

```
[Error] Chewing: symbols.dat cannot be found, please reinstall chewing package
[Info1] CHEWING_DATADIR_REAL=
```
