### ISSUE TITLE
unable to invoke function after pressing enter in search box of evernote.com

### ISSUE THREAD

**Issue by kidwm** [chewing/ibus-chewing#48]
Log in with your evernote account and click the search button on left panel.
Then type some words with ibus-chewing, it would fail to trigger the search function.

BUT…ibus-anthy did it successfully.

**Comment by definite** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1182821

**Comment by kidwm** [comment]
目前設定使用空白鍵選字後送不出空白字元的問題，應該跟這也有關係？

**Comment by definite** [comment]
ibus-chewing-1.5.0 應該可以在停用「空白鍵選字」後正常輸入。
不過在啟用「空白鍵選字」後的確產生無法輸入空白。這個應該另開一個issue

**Comment by definite** [comment]
啟用「空白鍵選字」後無法輸入空白 由 issue #79 追蹤
