### ISSUE TITLE
3 issues after updating from 1.4.8 to 1.4.14

### ISSUE THREAD

**Issue by yan12125** [chewing/ibus-chewing#49]
I've just updated ibus-chewing from 1.4.8 to 1.4.14 on my box and observed something different. First, when I'm tying, preedit texts are commited whenever I press Ctrl or End. It's observed in 1.4.14 but not in 1.4.8. Second, numpad keys does not work for selecting candidates. In 1.4.8, both numpad keys and ordinary number keys work, but in 1.4.14 only ordinary number keys work. Third, when I'm saving a file in firefox, filenames in the save file dialog disappear. For both ibus-anthy and ibus-sunpinyin, filenames are kept highlighted but in ibus-chewing, highlighted filenames disappeared immediately. Here is the system configuration of my box, and I hope them helpful on identifying these issues:

ibus-chewing 1.4.14
libchewing git-master(r1512)
ibus 1.5.9
OS: Arch Linux

**Comment by definite** [comment]
> I'm tying, preedit texts are commited whenever I press Ctrl or End
> This is fixed with #73, which will be release with 1.5.1
> 
> numpad keys does not work for selecting candidates
> Tracking with issue #88 
> 
> highlighted filenames disappeared immediately in firefox
> Tracking with issue #89
