### ISSUE TITLE
Hard-coded path in data/ibus-setup-chewing.desktop 

### ISSUE THREAD

**Issue by lantw44** [chewing/ibus-chewing#51]
`Exec=/usr/libexec/ibus-setup-chewing` is used in the desktop file. The path will be wrong if ibus-chewing is not configured to be installed in /usr.

**Comment by hiunnhue** [comment]
seems like commit ed621ea6e0885b06eaec86c865fd757ca5df3d5b has fixed this issue.

**Comment by definite** [comment]
Same as @hiunnhue said.
