### ISSUE TITLE
Having problems when leaving comments in Facebook

### ISSUE THREAD

**Issue by zerng07** [chewing/ibus-chewing#52]
Facebook is part of our (most are people who have smart phones) daily life now.

I think that Facebook has done something with comment box, so we are having problems typing nowadays. The problem is that the input box will eat your first key after you start typing.

How to reproduce:
1. Find one post you would like to comment to.
2. Move your cursor to  the the input box below the post and click to get the focus.
3. Switch to ibus-chewing
4. Start to type Chinese, and every first key after you start typing will be eaten by unknown monster. However, English mode (press Shift key) is fine.

Reproducible:
always

Hope this could be solved soon.....

**Comment by zerng07** [comment]
ibus-1.5.9
ibus-chewing-1.4.14

**Comment by pcchou** [comment]
Affected, too.

using firefox 37.0 right now

**Comment by lantw44** [comment]
This problem doesn't happen in Chromium and Epiphany.

**Comment by nykh** [comment]
Affected
Ubuntu
ibus 1.5.5
ibus-chewing 1.4.10.1-1
firefox 37.0

**Comment by hiunnhue** [comment]
我安裝了 Firefox 37 來測試，結果...
1. 只有留言欄異常，搜尋欄是正常的
2. 取消「在應用程式內嵌入預編文字」也能正常使用
3. Firefox 49 無此問題 

Env:
- ibus: 1.5.14
- ibus-chewing: 1.5.1
- Firefox: 37 & 49

**Comment by snyoung** [comment]
I have the Facebook problem on Firefox 49.
But the problem I encountered is that inserted text appears a column "before or after" the cursor (i.e. I can not predict exactly where it goes) and occasionally eat one character before it.
My workaround is inserting between blank lines or copy-and-pasting from elsewhere under English mode.

```
ibus 1.5.13
ibus-chewing 1.5.1
Firefox 49.0
```

on a fedora 24 system

**Comment by hiunnhue** [comment]
@snyoung 
抱歉，我不懂你的意思，你能再說明一下，或提供詳細的步驟嗎？

@其他朋友
請問你們升級到 Firefox 49 後還有「吃首鍵」（狀況 1）或其他問題嗎？

之前在測試的時候發現另一個問題，但現在又測不出來。當時沒馬上紀錄，印象中情況是這樣的：每當編輯緩衝區額滿時，ibus-chewing 會自動送出最前面的一個詞，接著收到 reset 訊號，所以緩衝區就被清空了。例如你輸入「是不是這樣的夜晚你才會這樣的想起我」，緩衝區額滿時，新酷音就會送出「是不是」，而剩下的字就全部消失（狀況 2）。

目前我在 firefox 49 上的情況則是：每當緩衝區額滿、自動送出，ibus-chewing 就會被 focus-out 再 focus-in 。Focus-out 的時候，ibus-chewing 會將緩衝區內的所有字都送出，所以不會造成太大的影響。（狀況 3）

總結來說，這些似乎是 firefox 本身的問題，和 ibus-chewing 比較沒有關係… 但如果各位有遇到上述的情形，可以試著把緩衝區字數調到最大，盡量自己按 enter 送出字，避免自動送出。

**Comment by snyoung** [comment]
我是指在留言框已經有中文字，要再插入的時候。實際插入的位置會跟游標差一格，而且有時候會取代掉「前面」本來就在那的字。

用GNOME Web 3.20開facebook也有完全一樣的bug，我不覺得這是firefox的問題。

**Comment by hiunnhue** [comment]
呣… 因為這些問題會隨著 Firefox 的版本而產生差異，例如 Firefox 37 有狀況 1，升級到 49 之後就沒了，所以我才推測是 Firefox 本身的問題…  :-(

我目前發現一個狀況，和你的問題有點相似，但是好像不會取代前面的字：
1. 先在留言欄輸入一些文字，按 enter 送出（變成不能選字）
2. 接著用方向鍵將游標移動幾個字，然後試著打字
3. 這時游標會自動跳回上一個字的位置（標記為狀況4）

這似乎是因為 ibus-chewing 把「放開按鍵」的事件給擋下了，所以導致游標沒辦法正確移動位置。#109 應該能解決這個問題。

**Comment by yan12125** [comment]
非常感謝 @hiunnhue 深入調查Firefox的問題！我也有遇到類似的問題。然而，由於Facebook的問題是不定時出現，請容我測試一段時間後再來回報。

PS. Firefox從46版開始使用GTK+3。我曾遇到一些Firefox的bug是GTK+2 only的，有些和輸入法相關的bug也可能在轉換至GTK+3之後消失。

**Comment by kidwm** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1302980
