### ISSUE TITLE
Highlighted text will be cleared after window (focus) switch under ibus-chewing

### ISSUE THREAD

**Issue by zerng07** [chewing/ibus-chewing#53]
How reproducible:
always

How to reproduce:
0. Having two windows of applications.
1. Switch to ibus-chewing, and input anything you want.
2. Highlighted those text.
3. Alt+Tab to switch to another window, and the highlighted text is cleared

This is so bothering when saving files which will prompt you a new dialogue box, and finding some words you would like to change which will prompt a new find and replace box. The monster eats the name of the files or the words found...

ibus-1.5.9
ibus-chewing-1.4.14

**Comment by lantw44** [comment]
This problem also happens when pressing Tab to switch the focus to a GtkEntry. If I remove the `commit_text` call in function `ibus_chewing_engine_focus_in` in `src/IBusChewingEngine-signal.c`, this problem can be fixed.

ibus-1.5.10
ibus-chewing-1.4.14
gtk-3.17.1-26-g578043f
