### ISSUE TITLE
Numpad does not work

### ISSUE THREAD

**Issue by dimotsai** [chewing/ibus-chewing#57]
Hi, all
I found that numpad does not work when I switch chewing to Chinese mode. This problem only happens on `ibus` + `libchewing` and only in Chinese mode. And I am sure that number keypad work fine on `fctix`.

Does anyone has the same problem?
- ibus 1.5.10
- ibus-chewing-1.4.14
- libchewing 0.4

A similar [issue](https://code.google.com/p/chewing/issues/detail?id=505) on google code.

**Comment by davy-tw** [comment]
me too

**Comment by definite** [comment]
Duplicate with Issue #88
