### ISSUE TITLE
1.4.14 build error: [Werror=format-security]

### ISSUE THREAD

**Issue by yochenhsieh** [chewing/ibus-chewing#58]
The following error encountered while building 1.4.14 rpm under Mageia cauldron:
/root/rpmbuild/BUILD/ibus-chewing-1.4.14/src/MakerDialogUtil.c: In function 'mkdg_g_value_to_string':
/root/rpmbuild/BUILD/ibus-chewing-1.4.14/src/MakerDialogUtil.c:124:6: error: format not a string literal and no format arguments [-Werror=format-security]
      g_value_get_string(value));
      ^
cc1: some warnings being treated as errors
bin/CMakeFiles/generate-gsettings-schemas.dir/build.make:226: recipe for target 'bin/CMakeFiles/generate-gsettings-schemas.dir/MakerDialogUtil.c.o' failed
make[2]: **\* [bin/CMakeFiles/generate-gsettings-schemas.dir/MakerDialogUtil.c.o] Error 1
CMakeFiles/Makefile2:519: recipe for target 'bin/CMakeFiles/generate-gsettings-schemas.dir/all' failed
make[1]: **\* [bin/CMakeFiles/generate-gsettings-schemas.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by yochenhsieh** [comment]
This commit can fix this issue:
https://github.com/definite/ibus-chewing/pull/54

**Comment by definite** [comment]
Pull request #54 fixed this issue.
