### ISSUE TITLE
GConf2 should be removed from INSTALL document

### ISSUE THREAD

**Issue by felixonmars** [chewing/ibus-chewing#61]
According to https://bugzilla.redhat.com/show_bug.cgi?id=902866#c3, the current ibus-chewing release provides dconf schema by default, and doesn't need GConf2. If this is the case, please remove it from the requirements to avoid confusion, thanks!

**Comment by definite** [comment]
Fixed in commit 224fca307e2f84084a783627c7e6b3f223682e35, as well as other dependencies.
