### ISSUE TITLE
Cannot build with 

### ISSUE THREAD

**Issue by czchen** [chewing/ibus-chewing#62]
From http://bugs.debian.org/806686, ibus-chewing cannot be built with cmake-fedora/2.4.4-1 in Debian.

The following error message is show when building on Debian:

```
    [Info1] MSGINIT_EXECUTABLE=/usr/bin/msginit
    [Off] MANAGE_ZANATA: Failed to find zanata.ini at /home/czchen/.config/zanata.ini
    CMake Error at /usr/share/cmake/Modules/ManageZanata.cmake:624 (ADD_CUSTOM_TARGET):
      add_custom_target cannot create target "zanata_push" because another target
      with the same name already exists.  The existing target is a custom target
      created in source directory
      "/mnt/disk/home/czchen/src/debian/ibus-chewing/po".  See documentation for
      policy CMP0002 for more details.
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/ManageZanata.cmake:713 (MANAGE_ZANATA_PUSH_TARGETS)
      po/CMakeLists.txt:6 (MANAGE_ZANATA)


    test GLIB2_LIBRARIES=gio-2.0;gmodule-2.0;gobject-2.0;gthread-2.0;glib-2.0
    test GLIB2_LIBRARIES=gio-2.0;gmodule-2.0;gobject-2.0;gthread-2.0;glib-2.0
    -- Configuring incomplete, errors occurred!
    See also "/mnt/disk/home/czchen/src/debian/ibus-chewing/CMakeFiles/CMakeOutput.log".
    debian/rules:24: recipe for target 'override_dh_auto_configure' failed
    make[1]: *** [override_dh_auto_configure] Error 1
    make[1]: Leaving directory '/mnt/disk/home/czchen/src/debian/ibus-chewing'
    debian/rules:8: recipe for target 'build' failed
    make: *** [build] Error 2
    dpkg-buildpackage: error: debian/rules build gave error exit status 2
    debuild: fatal error at line 1374:
    dpkg-buildpackage -rfakeroot -D -us -uc failed
```

**Comment by definite** [comment]
It looks like that cmake-fedora-2.4.3 is still detected/used.
Please try:
1 Update the cmake-fedora used in ibus-chewing to 2.4.4 

```
      cd cmake-fedora;  git fetch; git checkout 2.4.4; cd ..
```

2 Clean up old CMake file and rebuild

```
     ./wipe-rebuild.sh
```

Note that I assume you want gesttings_support=1, please inform me if thing does not work as expected.

**Comment by czchen** [comment]
Strange, looks like Debian cmake-fedora/2.4.4-1 uses the commit 87335d836abd3cc667d2645bab4dc6d1582a47eb, which is two commit behind the 2.4.4 version. Not sure why this commit is used as cmake-fedora/2.4.4-1 base version.

**Comment by czchen** [comment]
The upstream codebase uses for cmake-fedora/2.4.4-1 is in http://anonscm.debian.org/cgit/collab-maint/cmake-fedora.git/log/?h=upstream/latest

**Comment by czchen** [comment]
The release tarball downloaded from https://fedorahosted.org/releases/c/m/cmake-fedora/cmake-fedora-2.4.4-Source.tar.gz does not match the git tag in http://git.fedorahosted.org/git/cmake-fedora.git, please help to check if there is any problem.

**Comment by definite** [comment]
For cmake-fedora itself, the content should be no different between cmake-fedora-<version>-Source.tar.gz and cmake-fedora-<version>.tar.gz except the directory structure. 

cmake-fedora-<version>-Source.tar.gz extract to cmake-fedora-<version>-Source/
while
cmake-fedora-<version>.tar.gz extract to cmake-fedora-<version>/

For ibus-chewing, cmake-fedora is acted as git submodule.  I have updated cmake-fedora to 2.6.0, would you mind helping me to verify whether the it still working for you?

**Comment by definite** [comment]
@czchen Just wondering whether ibus-chewing-1.5.0 and cmake-fedora-2.6.0 works for you.

**Comment by definite** [comment]
@czchen I assume this issue is fixed. Please open a new issue if it does not work for you.
