### ISSUE TITLE
無法Ctrl加詞建立詞庫

### ISSUE THREAD

**Issue by astronid** [chewing/ibus-chewing#63]
無法使用Ctrl+數字鍵學習新的詞，只要一按Ctrl字就送出了無法停留在選字欄，因此無法學習詞彙

環境
ibus-chewing 1.4.14-2
libchewing3 0.4.0-3
Xubuntu 15.10

**Comment by definite** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1337185
