### ISSUE TITLE
RFE: Caps Lock 行為選項

### ISSUE THREAD

**Issue by definite** [chewing/ibus-chewing#66]
目前在 ibus-chewing 中，Caps Lock 被用來當作中英切換鍵。然而在英文環境中， Caps Lock 定義不清。
許多人習慣用 Caps Lock 來切換大小寫，在ibus-chewing 英文模式他們希望能夠保持這種習慣。

計畫方案如下：
增加兩個選項：
1. Caps Lock 切換中英文 (Boolean) 預設：「啟用」
2. 英文模式大小寫 (只在 Caps Lock 切換中英文模式起作用)
     a. 由 Caps Lock 決定 （預設值）
     b. 預設為小寫
     c. 預設為大寫

移除選項：「Caps Lock 時英數仍為小寫」

https://bugzilla.redhat.com/show_bug.cgi?id=1319403

**Comment by kidwm** [comment]
看來合理。
