### ISSUE TITLE
CPU usage very high when switch to Chewing Engine

### ISSUE THREAD

**Issue by bdsword** [chewing/ibus-chewing#68]
After I upgraded ibus-chewing to newest version on this repo, I found that the CPU usage is very high when I try to type under chewing input method.

In the source code, I also tried to find where the problem is.

Finally, I found the problem is located at function **ibus_chewing_systray_icon_update** in **src/IBusChewingSystray.c**. The **gtk_status_icon_set_from_file** function call cause a very high cpu usage whenever I press a key on the keyboard. (which call **ibus_chewing_systray_icon_update** at the end of function call chain)

refer: https://github.com/definite/ibus-chewing/blob/master/src/IBusChewingSystray.c#L101-L103

I'm not sure if I am the only one who faces this problem. But I suggest that you could preload all the four svg icons into memory(as GIcon or whatever), and use function like **gtk_status_icon_set_from_gicon** to set those icon for you.

**Comment by definite** [comment]
Thanks for suggestion. I would definitely try your suggestion. As well as revisit program logic to reduce the need to refresh the icon.

**Comment by definite** [comment]
@bdsword Please verify whether this mitigate the problem you encountered.

**Comment by bdsword** [comment]
@definite Sorry for the late reply.
I've seen your commit and applied it, but I found the problem is still there.

After some debugging... I noticed that the problem is caused by **g_ptr_array_insert** function in **ibus_chewing_systray_icon_update** of **IBusChewingSystray.c**.

The insertion causes the assertion failed. I've added some debug message in the source files, and show you the result [here](https://raw.githubusercontent.com/bdsword/ibus-chewing/add-issue-picture/code.png).

And since the insertion failed, ibus-chewing always loads icon file from disk, which cause the problem.

I also tried 1.5.0 on my ubuntu-gnome 16.04 LTS, the problem is the same.

Maybe check the manual of **g_ptr_array_insert** function.

**Comment by definite** [comment]
@bdsword Please verify whether this work for you

**Comment by bdsword** [comment]
@definite Thank you for your help! It works now.
The issue can be closed.
