### ISSUE TITLE
啟用「空白鍵選字」後無法輸入空白

### ISSUE THREAD

**Issue by definite** [chewing/ibus-chewing#79]
重現步驟：
1. 於設定中啟用「空白鍵選字」
2.按下空白鍵

期望：
 輸出空白

實際：
  無事發生

**Comment by hiunnhue** [comment]
引自 PIME

> NOTE: libchewing 有 bug: 當啟用 "使用空白鍵選字" 時，chewing_handle_Space() 會忽略空白鍵，造成打不出空白。因此在此只有當 composition string 有內容有需要選字時，才呼叫 handle_Space()，否則改用 handle_Default()，以免空白鍵被吃掉
