### ISSUE TITLE
數字版應當能用來選字

### ISSUE THREAD

**Issue by definite** [chewing/ibus-chewing#88]
Issue #49 指出，數字版應當用來選字。

期望行為：
英文模式應該照常輸出數字。
在中文模式：
    空模式（預編區為空）：
         偏好1（數字版總是輸出數字）：出現1
         偏好2（數字版數字等同主鍵區數字）：出現ㄅ

```
組字模式（預編區有未完成的字）：
     偏好1：不動作
     偏好2：不動作

選字模式（預編區有完成的字）：
     偏好1：插入數字
     偏好2：選字
```

**Comment by kidwm** [comment]
如果選字鍵設定不是 1234567890 其實可以總是輸出數字。

**Comment by definite** [comment]
@kidwm 你倒是提醒了我，應該要檢查1234567890是否用來選字。

**Comment by yan12125** [comment]
Subscribed.

**Comment by kidwm** [comment]
@yan12125 這種事可以不用出聲⋯

**Comment by hiunnhue** [comment]
是不是可以簡化一點？ 例如：
1. 通常不會特地用數字盤打ㄅㄆㄇ
2. 組字、選字時就專心組字、選字

整理過後如下：

```
英文模式：輸出123

中文模式
　　組字時：無反應（專心組字）
　　選字時+選字鍵非123：無反應（專心選字）
　　選字時+選字鍵是123：選字
　　預設：輸出123
```

這樣簡化之後，就可以把『數字板總是輸入數字，不負責選字』這個設定選項給移除了。

**Comment by definite** [comment]
@hiunnhue 好主意，就這麼辦吧

**Comment by kidwm** [comment]
或是在專心組選字時可以當方向鍵操作？

**Comment by definite** [comment]
@kidwm 那個功能你關掉 NumLock 就行了
