### ISSUE TITLE
firefox 另存新檔時，預編區的字丟失

### ISSUE THREAD

**Issue by definite** [chewing/ibus-chewing#89]
由Issue #49 提出。
重現步驟：
1. 進入「另存新檔」對話框。
2. 游標移到檔名輸入格，並清除預設檔名。
3. 打入「測試」，並按下Enter

期望：
  「測試」出現在檔名輸入格

現實：
  存入空檔名

**Comment by yan12125** [comment]
我從ibus-daemon的verbose log看，新酷音在出現空檔名的時候commit了一個empty string "" 可能commit的時機有誤。

**Comment by hiunnhue** [comment]
也許這個不是 ibus-chewing 的問題？

我發現，只要輸入欄位沒有跑出那張檔名清單，就不會發生這個錯誤。

清單跑出來的時候，可以先按方向鍵讓清單關閉，接著再輸入、按enter。

**Comment by yan12125** [comment]
抱歉我先前誤會的這個issue的steps to reproduce。我在 #49 提出的問題是：Save As的dailog一出現，ibus-chewing就會commit一個empty string。所以如果原本檔名是`foo.pdf`，會變成`.pdf`（GTK+會先把檔名foo反白）。在Firefox 47上已經沒有這個問題了。如同 @hiunnhue 所述，我猜可能是GTK+2的bug。Firefox 46開始預設是用GTK+3，所以這個bug也不復存在。

另外， @definite 所提的steps to reproduce我無法在firefox上重現。也許這個issue可以關了？

**Comment by definite** [comment]
我倒是可以 reproduce 這個

**Comment by definite** [comment]
後來又測了一下，@yan12125 講的是對的。 
Firefox 45 (RHEL 7)
Firefox 46.0.1 (Fedora 23) 都沒有這個問題。
