### ISSUE TITLE
Unable to use numeric keypad (on a full-size keyboard)

### ISSUE THREAD

**Issue by kaxing** [chewing/ibus-chewing#95]
The ten-key or so called "九宮格數字鍵" are not able to use while typing with ibus-chewing.
I could reproduce this on Ubuntu 16.04 with ibus-chewing 1.4.14-4.

So I wasn't notice this until I change the way I used to switch between English input.
If you are switching off ibus by system hotkey then you won't notice this, but by using shfit/capslock switching mode with ibus then the number keypad won't work.

redirect from ibus/ibus#1857

**Comment by yan12125** [comment]
Should work in git-master as #88 closed.

**Comment by definite** [comment]
Thanks @yan12125.
Please download ibus-chewing-1.5.1, which contained the fix for #88 (and this one).

**Comment by escrowdis** [comment]
Hi,
my version is 1.5.11 and I have the same issue of this on Ubuntu 16.04LTS (laptop user). Is there anyway to fix it up? 
Thanks!

**Comment by definite** [comment]
I am not sure Ubuntu, but right now there are no 1.5.11 in upstream.

**Comment by escrowdis** [comment]
@definite I've forgot how I found the version, so how to check the current version in right way? I've reinstalled it and still can't type the right-side number key. Is this still an issue?
Thank you!

**Comment by hiunnhue** [comment]
Hi, 我想您用的應該不是 1.5.11 而是 1.5.1-1 [1][2]。

我手邊沒有真正的數字鍵盤可以測試，但我用筆電的 Fn + NumLk 啟用數字鍵盤，是可以正常使用沒問題的……所以看不出問題在哪……

麻煩您先試試切換到其他輸入法，例如倉頡，或者乾脆關掉整個 ibus ( 在終端機輸入 ibus exit )，然後看看數字鍵盤是否正常。

--
[1] https://launchpad.net/ubuntu/+source/ibus-chewing
[2] https://packages.debian.org/sid/ibus-chewing

**Comment by escrowdis** [comment]
@hiunnhue 還是無法 
**env**: Ubuntu16.04.2 ibus 1.6.0, ACER V5 591G
Thank you for the advise

**Comment by escrowdis** [comment]
@definite Can this issue re-open? Thanks!

**Comment by hiunnhue** [comment]
@escrowdis 

您是說，在切換到倉頡或關掉整個 ibus  ( 在終端機輸入 ibus exit ) 之後，還是無法使用右邊的數字鍵盤嗎？是的話，這樣應該不是 ibus-chewing 的問題了。

也許是沒開啟 NumLock？ 請試試看
* 按著左下角的 `Fn` 鍵，再按數字鍵盤區的 `NumLock` 鍵
* 或不按 `Fn`，直接按 `NumLock`

**Comment by escrowdis** [comment]
@hiunnhue 對我關掉後有重新按過`Ctrl+NumLock`, `Fn+NumLock`, `Shift+NumLock`, ...能試的都按過了

之後又重新開始ibus-daemon 還是無法QQ

你覺得有可能是什麼狀況嗎? 

感謝~

**Comment by hiunnhue** [comment]
關閉 ibus ，**不再開啟**，直接按數字鍵盤，這樣還是沒反應？ ( 抱歉，好像在鬼打牆，我只是想確認 ) 這樣就不是 ibus-chewing 的問題。

如果是啟動 ibus-daemon 才不行，那……我束手無策了…… 囧

**Comment by yan12125** [comment]
FYI: 可在terminal輸入以下指令確認ibus是否正在執行。如果ibus有在執行，結果會類似如下：
```
$ pgrep -l ibus
5315 ibus-daemon
5322 ibus-dconf
5323 ibus-ui-gtk3
5334 ibus-engine-sim
5343 ibus-engine-che
```
而如果ibus沒有在執行則會沒有結果：
```
$ pgrep -l ibus

```
另外，可以從terminal中開啟xev這個小程式確認數字鍵盤是否有被X11顯示系統偵測到。無論ibus是否有開啟，xev按下數字鍵盤1的時候都會有類似以下的結果：
```
KeyPress event, serial 48, synthetic NO, window 0x2e00001,
    root 0xca, subw 0x0, time 1038909643, (416,803), root:(417,833),
    state 0x10, keycode 87 (keysym 0xffb1, KP_1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XmbLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False

KeyRelease event, serial 48, synthetic NO, window 0x2e00001,
    root 0xca, subw 0x0, time 1038909779, (416,803), root:(417,833),
    state 0x10, keycode 87 (keysym 0xffb1, KP_1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False
```

**Comment by escrowdis** [comment]
@hiunnhue 這之前有測過唷 `ibus exit` 後是可以使用的 嗚嗚感謝
This command `ibus exit` has been tested and the right-side num keyboard is OK after exit.

@yan12125 這工具很棒！ 超感謝的～測試完的結果是不管有沒有使用ibus或有沒有開都正常顯示這些資訊！ 
This command is very useful! Thank you very much and the output from typing some keys are the same whether the ibus is running or not.
